<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Breanna Ellis" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="introducing-dataset" class="section level2">
<h2>Introducing Dataset</h2>
<pre class="r"><code>library(tidyverse)
library(dplyr)
library(plotROC)
library(pROC)
library(rstatix)
library(lmtest)
baseball &lt;- read.csv(&quot;https://vincentarelbundock.github.io/Rdatasets/csv/vcd/Baseball.csv&quot;)


data(&quot;baseball&quot;)

#altering dataset
baseball &lt;- baseball %&gt;%
mutate(league86 = ifelse(league86 == &quot;N&quot;, 1, 0), div86 = ifelse(div86 == &quot;E&quot;, 1, 0)) %&gt;%
filter(complete.cases(.)) %&gt;%
select(name1, name2, atbat86, hits86, homer86, runs86, rbi86, walks86, years, atbat, hits, homeruns, runs, rbi, walks, league86, div86, team86, sal87)

#number of observations
length(baseball$name1)</code></pre>
<pre><code>## [1] 263</code></pre>
<p>baseball is a data set with numerous variables regarding the yearly batting records for all major league baseball players. The variables include name 1 (player's first name), name 2 (player's last name), atbat86 (number of times at bat in '86), hits86 (number of hits in '86), homer86 (number of home runs in '86), runs86 (the number of runs scored by each player in '86), rbi86 (number of &quot;runs batted in&quot; in '86), walks86 (number of walks awarded to the hitter in '86), years (years played in the major league), atbat (number of times at bat throughout the career), hits (number of hits in career), homer (number of home runs in career), runs (the number of runs scored by each player in career), rbi (number of &quot;runs batted in&quot; in career), walks (number of walks awarded to the hitter in career), league86 (player's league in '86), div86 (player's division in '86), team86 (player's team in '86), sal87 (player's salar in '87 in thousands of dollars). There are 263 observations.</p>
</div>
<div id="manova-test" class="section level2">
<h2>MANOVA test</h2>
<ul>
<li><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn't make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss MANOVA assumptions and whether or not they are likely to have been met (no need for anything too in-depth) (2).</li>
</ul>
<pre class="r"><code>#MANOVA
manbase1&lt;- (manova(cbind( homer86,hits86,runs86)~team86,data=baseball))
summary(manbase1)</code></pre>
<pre><code>##            Df  Pillai approx F num Df den Df Pr(&gt;F)
## team86     23 0.30342   1.1692     69    717 0.1726
## Residuals 239</code></pre>
<pre class="r"><code>summary.aov(manbase1)</code></pre>
<pre><code>## Response homer86 :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## team86 23 2211.4 96.149 1.2852 0.178
## Residuals 239 17880.6 74.814
##
## Response hits86 :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## team86 23 54946 2388.9 1.1931 0.2518
## Residuals 239 478564 2002.4
##
## Response runs86 :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## team86 23 24108 1048.16 1.7066 0.02607 *
## Residuals 239 146790 614.19
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>This MANOVA test found a p.value of 0.1726, therefore it is insignificant. Therefore, I did not continue with running the ANOVA tests.</p>
<pre class="r"><code>group &lt;- baseball$team86 
DVs &lt;- baseball %&gt;% select(homer86,hits86,runs86)
#Test multivariate normality for each group (null: assumption met)
sapply(split(DVs,group), mshapiro_test)</code></pre>
<pre><code>## Atl Bal Bos Cal Chi Cin Cle Det
## statistic 0.7761222 0.8892208 0.9007461 0.8216101
0.9054198 0.8113961 0.7952351 0.9215128
## p.value 0.0158075 0.1661813 0.2934552 0.02650363
0.03820944 0.0199371 0.00814257 0.3314424
## Hou KC LA Mil Min Mon NY
## statistic 0.6923028 0.8721604 0.6677027 0.5432095
0.8605039 0.5932832 0.8925912
## p.value 0.0007107557 0.1296734 0.0003585262 1.172356e-05
0.05845545 7.979433e-05 0.03001808
## Oak Phi Pit SD Sea SF StL Tex
## statistic 0.8263145 0.8779181 0.7888972 0.8263823
0.7910099 0.9152216 0.8529409 0.8291763
## p.value 0.05434261 0.1234924 0.01524052 0.0189897
0.007164501 0.2160939 0.04661639 0.02277103
## Tor
## statistic 0.8455319
## p.value 0.06652091</code></pre>
<pre class="r"><code>#If any p&lt;.05, stop (assumption violated). If not, test homogeneity of covariance matrices</code></pre>
<p>The pvalues that were less than 0.05 include Atl, Cal, Chi, Cin, Cle, Hou, LA, Mil, NY, Pit, SD, Sea, StL, and Tex. Assumptions were violated.</p>
</div>
<div id="randomization-test" class="section level2">
<h2>Randomization Test</h2>
<pre class="r"><code>#teams differ by salary
pairwise.t.test(baseball$sal87,baseball$team86, p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: baseball$sal87 and baseball$team86
##
## Atl Bal Bos Cal Chi Cin Cle Det Hou KC LA Mil
## Bal 0.91073 - - - - - - - - - - -
## Bos 0.26615 0.19930 - - - - - - - - - -
## Cal 0.26960 0.29266 0.02340 - - - - - - - - -
## Chi 0.32545 0.35482 0.02036 0.75715 - - - - - - - -
## Cin 0.38031 0.41689 0.04108 0.80945 0.97887 - - - - - -
-
## Cle 0.35480 0.38839 0.03449 0.82969 0.94827 0.97470 - -
- - - -
## Det 0.28359 0.30826 0.02385 0.95348 0.80230 0.85050
0.87237 - - - - -
## Hou 0.34302 0.37506 0.03462 0.86834 0.90854 0.93991
0.96375 0.91135 - - - -
## KC 0.40292 0.44191 0.04831 0.79798 0.99933 0.98303
0.95808 0.83760 0.92461 - - -
## LA 0.24860 0.26911 0.02056 0.95774 0.71038 0.76867
0.78767 0.91037 0.82685 0.75844 - -
## Mil 0.17912 0.19141 0.01231 0.79857 0.54299 0.61973
0.63391 0.74933 0.67382 0.61408 0.83975 -
## Min 0.24533 0.26525 0.01888 0.97033 0.71633 0.77641
0.79600 0.92202 0.83612 0.76585 0.98640 0.82275
## Mon 0.09533 0.09922 0.00518 0.53023 0.30485 0.38871
0.39513 0.48503 0.43026 0.38933 0.56453 0.70436
## NY 0.49047 0.37789 0.52178 0.03667 0.02524 0.06963
0.05639 0.03678 0.05738 0.08418 0.03157 0.01733
## Oak 0.41959 0.46001 0.05565 0.79950 0.99509 0.97873
0.95452 0.83800 0.92215 0.99528 0.76117 0.62094
## Phi 0.54483 0.60067 0.07614 0.59626 0.75495 0.77276
0.74347 0.62841 0.71576 0.79501 0.56008 0.43265
## Pit 0.07639 0.07862 0.00376 0.46013 0.24823 0.33065
0.33521 0.41700 0.36832 0.33260 0.49200 0.62377
## SD 0.29416 0.32007 0.02396 0.91636 0.83886 0.88325
0.90651 0.96278 0.94569 0.86914 0.87259 0.71024
## Sea 0.03427 0.03317 0.00101 0.28888 0.11602 0.19145
0.19151 0.25169 0.21887 0.19649 0.31417 0.42367
## SF 0.02668 0.02500 0.00062 0.25778 0.09016 0.16552
0.16451 0.22105 0.19119 0.17140 0.28214 0.38916
## StL 0.64222 0.70958 0.09732 0.48051 0.60612 0.64629
0.61516 0.50720 0.59194 0.67127 0.44748 0.33398
## Tex 0.04792 0.04744 0.00163 0.36206 0.16274 0.24709
0.24867 0.32046 0.27988 0.25143 0.39126 0.51522
## Tor 0.98781 0.92067 0.24632 0.26121 0.31383 0.37370
0.34718 0.27484 0.33568 0.39733 0.24004 0.17046
## Min Mon NY Oak Phi Pit SD Sea SF StL Tex
## Bal - - - - - - - - - - -
## Bos - - - - - - - - - - -
## Cal - - - - - - - - - - -
## Chi - - - - - - - - - - -
## Cin - - - - - - - - - - -
## Cle - - - - - - - - - - -
## Det - - - - - - - - - - -
## Hou - - - - - - - - - - -
## KC - - - - - - - - - - -
## LA - - - - - - - - - - -
## Mil - - - - - - - - - - -
## Min - - - - - - - - - - -
## Mon 0.54485 - - - - - - - - - -
## NY 0.02796 0.00647 - - - - - - - - -
## Oak 0.76856 0.40030 0.09883 - - - - - - - -
## Phi 0.56231 0.25339 0.13790 0.80599 - - - - - - -
## Pit 0.47218 0.91374 0.00441 0.34420 0.21028 - - - - - -
## SD 0.88340 0.44977 0.03630 0.86858 0.65387 0.38356 - - -
- -
## Sea 0.29431 0.69634 0.00078 0.20923 0.10961 0.78201
0.22350 - - - -
## SF 0.26174 0.66446 0.00035 0.18471 0.09074 0.75196
0.19338 0.97529 - - -
## StL 0.44670 0.18497 0.17975 0.68596 0.87018 0.15028
0.52814 0.07105 0.05627 - -
## Tex 0.37031 0.80653 0.00141 0.26457 0.14666 0.89554
0.28853 0.87818 0.84891 0.09827 -
## Tor 0.23623 0.08850 0.46105 0.41493 0.54255 0.07020
0.28508 0.02989 0.02268 0.64281 0.04255
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>#teams differ by homers
pairwise.t.test(baseball$homer86,baseball$team86, p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: baseball$homer86 and baseball$team86
##
## Atl Bal Bos Cal Chi Cin Cle Det Hou KC LA Mil
## Bal 0.63936 - - - - - - - - - - -
## Bos 0.35595 0.61350 - - - - - - - - - -
## Cal 0.44701 0.75666 0.83130 - - - - - - - - -
## Chi 0.71473 0.85151 0.45149 0.58204 - - - - - - - -
## Cin 0.60498 0.95881 0.64808 0.79623 0.80433 - - - - - -
-
## Cle 0.32753 0.59383 0.98873 0.82879 0.40997 0.63089 - -
- - - -
## Det 0.09829 0.21046 0.50705 0.34912 0.09441 0.23027
0.46035 - - - - -
## Hou 0.76552 0.85655 0.49946 0.62374 0.98023 0.81622
0.47270 0.15093 - - - -
## KC 0.76893 0.86253 0.51142 0.63501 0.98353 0.82321
0.48690 0.16346 0.99777 - - -
## LA 0.68345 0.35296 0.16790 0.21586 0.36695 0.32691
0.13844 0.02818 0.45417 0.46458 - -
## Mil 0.81236 0.45417 0.22649 0.29025 0.48979 0.42369
0.19439 0.04419 0.57006 0.57848 0.85655 -
## Min 0.08951 0.19357 0.47859 0.32501 0.08382 0.21221
0.43103 0.96072 0.13781 0.14988 0.02495 0.03942
## Mon 0.83526 0.48178 0.24724 0.31519 0.52441 0.45107
0.21643 0.05345 0.59770 0.60511 0.84064 0.97995
## NY 0.17476 0.37140 0.79845 0.59154 0.17703 0.40408
0.76262 0.59136 0.27049 0.28907 0.04997 0.07948
## Oak 0.48856 0.79354 0.81734 0.97572 0.63583 0.83130
0.81466 0.36203 0.66567 0.67509 0.25565 0.33360
## Phi 0.88866 0.51871 0.26593 0.33977 0.56890 0.48585
0.23307 0.05641 0.64212 0.64901 0.77637 0.91773
## Pit 0.89234 0.73333 0.41518 0.52081 0.82960 0.69584
0.38637 0.11790 0.86912 0.87026 0.57277 0.69790
## SD 0.95796 0.56514 0.28752 0.36900 0.62591 0.52927
0.25136 0.05795 0.69908 0.70524 0.69244 0.83618
## Sea 0.52160 0.86264 0.72408 0.88536 0.69064 0.90437
0.71191 0.26846 0.72035 0.72997 0.26139 0.34789
## SF 0.60216 0.27824 0.12219 0.15790 0.27140 0.25471
0.09322 0.01480 0.37203 0.38490 0.92260 0.77233
## StL 0.16464 0.04754 0.01766 0.02178 0.03152 0.04198
0.01024 0.00101 0.07210 0.07986 0.29978 0.22201
## Tex 0.38626 0.67943 0.89886 0.92343 0.49521 0.71855
0.90202 0.38916 0.54976 0.56286 0.17312 0.23874
## Tor 0.21405 0.40559 0.76893 0.59577 0.25208 0.43450
0.73975 0.71249 0.31385 0.32758 0.08332 0.11941
## Min Mon NY Oak Phi Pit SD Sea SF StL Tex
## Bal - - - - - - - - - - -
## Bos - - - - - - - - - - -
## Cal - - - - - - - - - - -
## Chi - - - - - - - - - - -
## Cin - - - - - - - - - - -
## Cle - - - - - - - - - - -
## Det - - - - - - - - - - -
## Hou - - - - - - - - - - -
## KC - - - - - - - - - - -
## LA - - - - - - - - - - -
## Mil - - - - - - - - - - -
## Min - - - - - - - - - - -
## Mon 0.04799 - - - - - - - - - -
## NY 0.55335 0.09611 - - - - - - - - -
## Oak 0.33878 0.35747 0.59521 - - - - - - - -
## Phi 0.05054 0.93989 0.10194 0.38444 - - - - - - -
## Pit 0.10739 0.72346 0.21087 0.56360 0.77362 - - - - - -
## SD 0.05168 0.86139 0.10541 0.41722 0.92122 0.83859 - - -
- -
## Sea 0.24782 0.37512 0.47077 0.91677 0.40472 0.60560
0.44078 - - - -
## SF 0.01286 0.75863 0.02493 0.19697 0.68980 0.48914
0.59954 0.19467 - - -
## StL 0.00086 0.22520 0.00135 0.03334 0.18471 0.11372
0.13651 0.02747 0.31426 - -
## Tex 0.36268 0.26281 0.65861 0.90333 0.28335 0.45346
0.30690 0.80552 0.12077 0.01441 -
## Tor 0.67799 0.13525 0.92867 0.59519 0.14500 0.25356
0.15475 0.49506 0.05393 0.00573 0.65348
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>baseball%&gt;%select(team86,sal87,homer86)%&gt;%pivot_longer(-1,names_to=&#39;DV&#39;, values_to=&#39;measure&#39;)%&gt;%
  ggplot(aes(team86,measure,fill=team86))+geom_bar(stat=&quot;summary&quot;)+geom_errorbar(stat=&quot;summary&quot;, width=.5)+
  facet_wrap(~DV, nrow=2)+coord_flip()+ylab(&quot;&quot;)+theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
</div>
<div id="linear-regression" class="section level2">
<h2>Linear Regression</h2>
<pre class="r"><code>data(&quot;baseball&quot;)
sal87fix &lt;- baseball$sal87-(mean(baseball$sal87, na.rm=T))
atbat86fix &lt;- baseball$atbat86-(mean(baseball$atbat86, na.rm=T))
hits86fix &lt;- baseball$hits86-(mean(baseball$hits86, na.rm=T))
homer86fix &lt;- baseball$homer86-(mean(baseball$homer86, na.rm=T))
runs86fix &lt;- baseball$runs86-(mean(baseball$runs86, na.rm=T))
rbi86fix &lt;- baseball$rbi86-(mean(baseball$rbi86, na.rm=T))

#linear regression
baseballfit &lt;- lm(sal87fix ~ atbat86fix + hits86fix + homer86fix + runs86fix + rbi86fix, data = baseball)
summary(baseballfit)</code></pre>
<pre><code>##
## Call:
## lm(formula = sal87fix ~ atbat86fix + hits86fix +
homer86fix +
## runs86fix + rbi86fix, data = baseball)
##
## Residuals:
## Min 1Q Median 3Q Max
## -917.82 -228.03 -73.24 177.95 1992.97
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 3.499e-14 2.442e+01 0.000 1.00000
## atbat86fix -1.802e+00 6.487e-01 -2.779 0.00586 **
## hits86fix 6.309e+00 2.359e+00 2.674 0.00797 **
## homer86fix -3.432e+00 6.425e+00 -0.534 0.59376
## runs86fix 2.039e+00 2.654e+00 0.768 0.44309
## rbi86fix 6.746e+00 2.822e+00 2.390 0.01755 *
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 396 on 257 degrees of freedom
## Multiple R-squared: 0.2441, Adjusted R-squared: 0.2294
## F-statistic: 16.6 on 5 and 257 DF, p-value: 3.372e-14</code></pre>
<pre class="r"><code>#graph 
baseballfit %&gt;% ggplot(aes(sal87fix, 
    sal87fix, color = runs86fix)) + geom_point() + geom_smooth(method = &quot;lm&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-5-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>Holding all other variables constant, a player increasing their yearly RBI total by 1, increased their salary by approximately 6.74 thousand dollars, increasing their yearly at bat total by 1 decreased their salary by approximately 1.80 thousand dollars in 1987, increasing their hits total by 1 increased their salary by 6.30 thousand dollars in 1987, increasing their yearly homer total by 1 decreased their salary by approximately 3.43 thousand dollars in 1987, increasing their yearly run total by 1 increased their salary by approximately 2.03 thousand dollars in 1987 and for a player with 0 bats, hits, homeruns, runs, and rbis, the approximate salary for a player in 1987 was 3.49e-14 thousand dollars. Based on the adjusted R-squared value, 22.94% of the variation in the data can be explained.</p>
<pre class="r"><code>#linearity, normality, and homoskedasticity 
#homoskedasticity test
library(sandwich)
library(lmtest)
bptest(baseballfit) #test assumption: violated!</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  baseballfit
## BP = 12.465, df = 5, p-value = 0.02894</code></pre>
<pre class="r"><code>coeftest(baseballfit, vcov = vcovHC(baseballfit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 3.4987e-14 2.4948e+01 0.0000 1.00000
## atbat86fix -1.8023e+00 7.8041e-01 -2.3095 0.02171 *
## hits86fix 6.3090e+00 2.8983e+00 2.1768 0.03041 *
## homer86fix -3.4315e+00 8.0943e+00 -0.4239 0.67196
## runs86fix 2.0385e+00 3.0850e+00 0.6608 0.50935
## rbi86fix 6.7458e+00 3.9193e+00 1.7212 0.08642 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>#check assumptions
ggplot(mapping = aes(x=baseballfit$fitted.values, y=baseballfit$residuals)) + geom_point() + geom_hline(yintercept = 0) + geom_smooth()</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(mapping = aes(sample = scale(baseballfit$residuals))) + geom_qq() + geom_qq_line()</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<p>running the &quot;coeftest(baseballfit, vcov = vcovHC(baseballfit))&quot; did not alter the t-test coefficients. The residuals are not linearly distributed as there is significant curving towards the beginning and end of the graph. The normality assumption is not met as the graph curves towards the end. The homoskedasticity assumption does not seem reasonable either.</p>
</div>
<div id="rerun-regression" class="section level2">
<h2>Rerun Regression</h2>
<pre class="r"><code>### Bootstrapping residuals

fit&lt;-lm(sal87fix ~ atbat86fix + hits86fix + homer86fix + runs86fix + rbi86fix, data = baseball) #fit model
resids&lt;-fit$residuals #save residuals
fitted&lt;-fit$fitted.values #save yhats/predictions

resid_resamp&lt;-replicate(5000,{
new_resids&lt;-sample(resids,replace=TRUE) #resample resids w/ replacement
baseball$sal87fix&lt;-fitted+new_resids #add new resids to yhats to get new &quot;data&quot;
fit&lt;-lm(sal87fix ~ atbat86fix + hits86fix + homer86fix + runs86fix + rbi86fix, data = baseball) 
coef(fit)
}) 

resid_resamp%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>## (Intercept) atbat86fix hits86fix homer86fix runs86fix
rbi86fix
## 1 24.50104 0.6304676 2.271548 6.348248 2.583727 2.810736</code></pre>
<p>All of the variables were altered as compared to the previous SEs.</p>
</div>
<div id="logistic-regression" class="section level2">
<h2>Logistic Regression</h2>
<pre class="r"><code>library(plotROC)
baseballfitleag&lt;-glm(league86~sal87+homer86, data=baseball, family=&quot;binomial&quot;)
coef(baseballfitleag)%&gt;%exp%&gt;%round(5)%&gt;%data.frame</code></pre>
<pre><code>##                   .
## (Intercept) 1.48222
## sal87       1.00035
## homer86     0.94091</code></pre>
<pre class="r"><code>coeftest(baseballfitleag)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 0.39354301 0.23232584 1.6939 0.0902792 .
## sal87 0.00034701 0.00030808 1.1264 0.2600097
## homer86 -0.06090276 0.01667951 -3.6514 0.0002609 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>baseball$prob &lt;- predict(baseballfitleag,type=&quot;response&quot;)

# predicted outcomes (if prob&gt;.5, predict 0, otherwise predict 1)
baseball$predicted &lt;- ifelse(baseball$prob&gt;.5,&quot;0&quot;,&quot;1&quot;)</code></pre>
<p>From the coefficient estimates and their respective significance values, league and home runs in 1986 appear to be significant.</p>
<pre class="r"><code># confusion matrix
table(truth=baseball$league86, prediction=baseball$predicted)%&gt;%addmargins</code></pre>
<pre><code>##      prediction
## truth   0   1 Sum
##   0    59  80 139
##   1    73  51 124
##   Sum 132 131 263</code></pre>
<pre class="r"><code># accuracy: proportion of all cases that were correctly classified
(59+51)/263</code></pre>
<pre><code>## [1] 0.418251</code></pre>
<pre class="r"><code>#sensitivity: proportion of true that were correctly classified
51/131</code></pre>
<pre><code>## [1] 0.389313</code></pre>
<pre class="r"><code># specificity: proportion of false cases that were correctly classified
59/132</code></pre>
<pre><code>## [1] 0.4469697</code></pre>
<pre class="r"><code># plot
library(plotROC)
baseball$logit&lt;-predict(baseballfitleag)</code></pre>
<pre class="r"><code># ROC and AUC
baseballROC&lt;- ggplot(baseball)+geom_roc(aes(d=league86, m=prob), n.cuts=0)
baseballROC</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-10-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(baseballROC)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.6131063</code></pre>
<pre class="r"><code>baseball$logit&lt;-predict(baseballfitleag)
baseball %&gt;% ggplot(aes(logit, fill=league86)) + geom_density(alpha=.3)+geom_vline(xintercept=0, lty=2)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-10-2.png" width="768" style="display: block; margin: auto;" /> The AUC value is 0.613, which is not ideal.</p>
</div>
<div id="more-logistic-regression" class="section level2">
<h2>More Logistic Regression</h2>
<pre class="r"><code>library(glmnet)
set.seed(1234)
baseball_resp &lt;- as.matrix(baseball$league86)  #response
baseball_preds &lt;- model.matrix(league86 ~ ., data = baseball)[, -1]
head(baseball_preds)  #prediction</code></pre>
<pre><code>## name1Alan name1Alex name1Alfredo name1Alvin name1Andre
name1Andres name1Andy name1Argenis
## 1 0 0 0 0 0 0 0 0
## 2 1 0 0 0 0 0 0 0
## 3 1 0 0 0 0 0 0 0
## 4 1 0 0 0 0 0 0 0
## 5 0 1 0 0 0 0 0 0
## 6 0 0 1 0 0 0 0 0
## name1Barry name1Ben name1Bill name1Billy name1Billy Jo
name1Bip name1Bo name1Bob name1Bobby
## 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0 0
## name1Brett name1Brian name1Brook name1Bruce name1Buddy
name1Butch name1Cal name1Candy
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name1Carlton name1Carmelo name1Carmen name1Carney
name1Cecil name1Charlie name1Chet name1Chili
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name1Chris name1Cliff name1Cory name1Craig name1Curt
name1Dale name1Damaso name1Dan name1Dann
## 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0 0
## name1Danny name1Darnell name1Darrell name1Darren
name1Darryl name1Daryl name1Dave name1Davey
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name1Denny name1Dick name1Dickie name1Don name1Donnie
name1Doug name1Dwayne name1Dwight name1Ed
## 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0 0
## name1Eddie name1Enos name1Eric name1Ernest name1Ernie
name1Floyd name1Frank name1Franklin
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name1Fred name1Garry name1Garth name1Gary name1George
name1Glenn name1Gorman name1Graig name1Greg
## 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0 0
## name1Hal name1Harold name1Harry name1Herm name1Howard
name1Hubie name1Jack name1Jamie name1Jeff
## 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0 0
## name1Jeffrey name1Jerry name1Jesse name1Jim name1Jody
name1Joe name1Joel name1John name1Johnny
## 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0 0
## name1Jorge name1Jose name1Juan name1Julio name1Kal
name1Keith name1Ken name1Kent name1Kevin
## 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0 0
## name1Kirby name1Kirk name1Kurt name1Lance name1Larry
name1Lee name1Len name1Leon name1Lloyd
## 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0 0
## name1Lonnie name1Lou name1Luis name1Mariano name1Mark
name1Marty name1Marvell name1Mel
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name1Mickey name1Mike name1Milt name1Mitch name1Mookie
name1Nick name1Oddibe name1Omar name1Ozzie
## 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0 0
## name1Pat name1Paul name1Pete name1Phil name1Rafael
name1Rance name1Randy name1Ray name1Reggie
## 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0 0
## name1Rey name1Rich name1Rick name1Rickey name1Ricky
name1Rob name1Robby name1Robin name1Ron
## 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0 0
## name1Ronn name1Roy name1Ruben name1Rudy name1Ryne
name1Scott name1Shawon name1Sid name1Spike
## 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0 0
## name1Steve name1Ted name1Terry name1Tim name1Tito
name1Toby name1Tom name1Tommy name1Tony
## 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0 0
## name1Vance name1Vince name1Von name1Wade name1Wally
name1Wayne name1Will name1Willie
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Allanson name2Almon name2Anderson name2Armas
name2Ashby name2Backman name2Baines name2Baker
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 1 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Balboni name2Bando name2Barfield name2Barrett
name2Bass name2Baylor name2Beane name2Bell
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Belliard name2Beniquez name2Bernazard
name2Biancalana name2Bilardello name2Bochte name2Bochy
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Boggs name2Bonds name2Bonilla name2Boone
name2Boston name2Bradley name2Braggs name2Bream
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Brenly name2Brett name2Brock name2Brookens
name2Brooks name2Brown name2Brunansky
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Buckner name2Buechele name2Burleson name2Bush
name2Butler name2Cabell name2Cangelosi
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Canseco name2Carter name2Castillo name2Cerone
name2Cey name2Clark name2Coleman name2Coles
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Collins name2Concepcion name2Cooper name2Cruz
name2Daniels name2Daulton name2Davis
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Dawson name2DeCinces name2Deer name2Dempsey
name2Dernier name2Diaz name2Doran name2Downing
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Duncan name2Dunston name2Durham name2Dwyer
name2Dykstra name2Easler name2Esasky name2Evans
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Fernandez name2Fisk name2Fitzgerald name2Flannery
name2Fletcher name2Foley name2Ford
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Foster name2Franco name2Gaetti name2Gagne
name2Galarraga name2Gantner name2Garcia
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Garner name2Garvey name2Gedman name2Gibson
name2Gladden name2Grich name2Griffey name2Griffin
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 1
## name2Grubb name2Guillen name2Gwynn name2Hairston
name2Hall name2Harper name2Harrah name2Hassey
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Hatcher name2Hayes name2Heath name2Heep
name2Henderson name2Hendrick name2Hernandez
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Herndon name2Herr name2Hill name2Horner name2Howell
name2Hrbek name2Hubbard name2Hulett
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Incaviglia name2Iorg name2Jackson name2Jacoby
name2Jeltz name2Johnson name2Jones name2Joyner
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Kearney name2Kennedy name2Kingery name2Kingman
name2Kittle name2Knight name2Krenchicki
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Kruk name2Kutcher name2Lacy name2Landreaux
name2Landrum name2Lansford name2Laudner
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2LaValliere name2Law name2Leach name2Lemon
name2Leonard name2Lombardozzi name2Lopes name2Lynn
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Madlock name2Maldonado name2Manning name2Marshall
name2Martinez name2Matthews name2Mattingly
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Matuszek name2McDowell name2McGee name2McRae
name2McReynolds name2Meacham name2Melvin
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Milner name2Mitchell name2Molitor name2Moore
name2Moreland name2Moreno name2Morrison
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Moseby name2Moses name2Motley name2Mulliniks
name2Mumphrey name2Murphy name2Murray
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Nettles name2Newman name2O&#39;Brien name2O&#39;Malley
name2Oberkfell name2Oester name2Oglivie
## 1 0 1 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Orsulak name2Orta name2Owen name2Paciorek
name2Pagliarulo name2Parker name2Parrish
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Pasqua name2Pena name2Pendleton name2Perez
name2Pettis name2Phelps name2Phillips name2Porter
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Presley name2Puckett name2Puhl name2Quinones
name2Quirk name2Raines name2Ramirez
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Randolph name2Ray name2Rayford name2Redus name2Reed
name2Reynolds name2Rice name2Riles
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Ripken name2Rivera name2Roberts name2Robidoux
name2Roenicke name2Romero name2Rose
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Royster name2Russell name2Salas name2Salazar
name2Sample name2Samuel name2Sandberg
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Santana name2Sax name2Schmidt name2Schofield
name2Schroeder name2Schu name2Scioscia
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Sheets name2Shelby name2Sheridan name2Sierra
name2Simmons name2Skinner name2Slaught
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Smalley name2Smith name2Snyder name2Speier
name2Spilman name2Stillwell name2Stone
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Strawberry name2Stubbs name2Sundberg name2Sveum
name2Tabler name2Tartabull name2Templeton
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Tettleton name2Teufel name2Thomas name2Thompson
name2Thon name2Thornton name2Tolleson
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Traber name2Trammell name2Trevino name2Upshaw
name2Uribe name2Van Slyke name2Virgil
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 1 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 1 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Walker name2Wallach name2Walling name2Ward
name2Webster name2Whitaker name2White name2Whitt
## 1 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0 0
## name2Wiggins name2Wilfong name2Wilkerson name2Willard
name2Williams name2Wilson name2Winfield
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 1 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## name2Winningham name2Wynegar name2Wynne name2Young
name2Youngblood name2Yount atbat86 hits86
## 1 0 0 0 0 0 0 185 37
## 2 0 0 0 0 0 0 315 81
## 3 0 0 0 0 0 0 574 159
## 4 0 0 0 0 0 0 239 60
## 5 0 0 0 0 0 0 202 53
## 6 0 0 0 0 0 0 594 169
## homer86 runs86 rbi86 walks86 years atbat hits homeruns
runs rbi walks div86 team86Bal team86Bos
## 1 1 23 8 21 2 214 42 1 30 9 24 1 0 0
## 2 7 24 38 39 14 3449 835 69 321 414 375 0 0 0
## 3 21 107 75 59 10 4631 1300 90 702 504 488 1 0 0
## 4 0 30 11 22 6 1941 510 4 309 103 207 1 1 0
## 5 4 31 26 27 9 1876 467 15 192 186 161 0 0 0
## 6 4 74 51 35 11 4408 1133 19 501 336 194 0 0 0
## team86Cal team86Chi team86Cin team86Cle team86Det
team86Hou team86KC team86LA team86Mil team86Min
## 1 0 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 1 0 0 0 0
## 3 0 0 0 0 1 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 1 0 0
## 6 0 0 0 0 0 0 0 0 0 0
## team86Mon team86NY team86Oak team86Phi team86Pit
team86SD team86Sea team86SF team86StL team86Tex
## 1 1 0 0 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0 0 0 0
## 6 0 0 1 0 0 0 0 0 0 0
## team86Tor sal87 prob predicted1 logit
## 1 0 70.000 0.5882974 0 0.3569312
## 2 0 475.000 0.5329659 0 0.1320554
## 3 0 517.143 0.3304923 1 -0.7059591
## 4 0 700.000 0.6539512 0 0.6364529
## 5 0 512.500 0.5812183 0 0.3277767
## 6 0 750.000 0.6011340 0 0.4101925</code></pre>
<pre class="r"><code>cv &lt;- cv.glmnet(baseball_preds, baseball_resp, family = &quot;binomial&quot;)  #picks an optimal value for lambda through 10-fold CV

cv &lt;- cv.glmnet(baseball_preds, baseball_resp, family = &quot;binomial&quot;)
lasso_fit &lt;- glmnet(baseball_preds, baseball_resp, family = &quot;binomial&quot;, 
    lambda = cv$lambda.1se)
coef(lasso_fit)</code></pre>
<pre><code>## 508 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                            s0
## (Intercept)       0.117519943
## name1Alan         .          
## name1Alex         .          
## name1Alfredo      .          
## name1Alvin        .          
## name1Andre        .          
## name1Andres       .          
## name1Andy         .          
## name1Argenis      .          
## name1Barry        .          
## name1Ben          .          
## name1Bill         .          
## name1Billy        .          
## name1Billy Jo     .          
## name1Bip          .          
## name1Bo           .          
## name1Bob          .          
## name1Bobby        .          
## name1Brett        .          
## name1Brian        .          
## name1Brook        .          
## name1Bruce        .          
## name1Buddy        .          
## name1Butch        .          
## name1Cal          .          
## name1Candy        .          
## name1Carlton      .          
## name1Carmelo      .          
## name1Carmen       .          
## name1Carney       .          
## name1Cecil        .          
## name1Charlie      .          
## name1Chet         .          
## name1Chili        .          
## name1Chris        .          
## name1Cliff        .          
## name1Cory         .          
## name1Craig        .          
## name1Curt         .          
## name1Dale         .          
## name1Damaso       .          
## name1Dan          .          
## name1Dann         .          
## name1Danny        .          
## name1Darnell      .          
## name1Darrell      .          
## name1Darren       .          
## name1Darryl       0.025583991
## name1Daryl        .          
## name1Dave         .          
## name1Davey        .          
## name1Denny        .          
## name1Dick         .          
## name1Dickie       .          
## name1Don          .          
## name1Donnie       .          
## name1Doug         .          
## name1Dwayne       .          
## name1Dwight       .          
## name1Ed           .          
## name1Eddie        .          
## name1Enos         .          
## name1Eric         .          
## name1Ernest       .          
## name1Ernie        .          
## name1Floyd        .          
## name1Frank        .          
## name1Franklin     .          
## name1Fred         .          
## name1Garry        .          
## name1Garth        .          
## name1Gary         .          
## name1George       .          
## name1Glenn        .          
## name1Gorman       .          
## name1Graig        .          
## name1Greg         .          
## name1Hal          .          
## name1Harold       .          
## name1Harry        .          
## name1Herm         .          
## name1Howard       .          
## name1Hubie        .          
## name1Jack         .          
## name1Jamie        .          
## name1Jeff         .          
## name1Jeffrey      .          
## name1Jerry        .          
## name1Jesse        .          
## name1Jim          .          
## name1Jody         .          
## name1Joe          .          
## name1Joel         .          
## name1John         .          
## name1Johnny       .          
## name1Jorge        .          
## name1Jose         .          
## name1Juan         .          
## name1Julio        .          
## name1Kal          .          
## name1Keith        0.507950989
## name1Ken          .          
## name1Kent         .          
## name1Kevin        .          
## name1Kirby        .          
## name1Kirk         .          
## name1Kurt         .          
## name1Lance        .          
## name1Larry        .          
## name1Lee          .          
## name1Len          .          
## name1Leon         .          
## name1Lloyd        .          
## name1Lonnie       .          
## name1Lou          .          
## name1Luis         .          
## name1Mariano      .          
## name1Mark         .          
## name1Marty        .          
## name1Marvell      .          
## name1Mel          .          
## name1Mickey       .          
## name1Mike         .          
## name1Milt         .          
## name1Mitch        .          
## name1Mookie       .          
## name1Nick         .          
## name1Oddibe       .          
## name1Omar         .          
## name1Ozzie        .          
## name1Pat          .          
## name1Paul         .          
## name1Pete         .          
## name1Phil         .          
## name1Rafael       0.321292904
## name1Rance        .          
## name1Randy        .          
## name1Ray          .          
## name1Reggie       .          
## name1Rey          .          
## name1Rich         .          
## name1Rick         .          
## name1Rickey       .          
## name1Ricky        .          
## name1Rob          .          
## name1Robby        .          
## name1Robin        .          
## name1Ron          .          
## name1Ronn         .          
## name1Roy          .          
## name1Ruben        .          
## name1Rudy         .          
## name1Ryne         .          
## name1Scott        .          
## name1Shawon       .          
## name1Sid          .          
## name1Spike        .          
## name1Steve        .          
## name1Ted          .          
## name1Terry        .          
## name1Tim          .          
## name1Tito         .          
## name1Toby         .          
## name1Tom          .          
## name1Tommy        .          
## name1Tony         .          
## name1Vance        .          
## name1Vince        .          
## name1Von          .          
## name1Wade         .          
## name1Wally        .          
## name1Wayne        .          
## name1Will         .          
## name1Willie       .          
## name2Allanson     .          
## name2Almon        .          
## name2Anderson     .          
## name2Armas        .          
## name2Ashby        .          
## name2Backman      .          
## name2Baines       .          
## name2Baker        .          
## name2Balboni      .          
## name2Bando        .          
## name2Barfield     .          
## name2Barrett      .          
## name2Bass         .          
## name2Baylor       .          
## name2Beane        .          
## name2Bell         .          
## name2Belliard     .          
## name2Beniquez     .          
## name2Bernazard    .          
## name2Biancalana   .          
## name2Bilardello   .          
## name2Bochte       .          
## name2Bochy        .          
## name2Boggs        .          
## name2Bonds        .          
## name2Bonilla      .          
## name2Boone        .          
## name2Boston       .          
## name2Bradley      .          
## name2Braggs       .          
## name2Bream        .          
## name2Brenly       .          
## name2Brett        .          
## name2Brock        .          
## name2Brookens     .          
## name2Brooks       .          
## name2Brown        .          
## name2Brunansky    .          
## name2Buckner      .          
## name2Buechele     .          
## name2Burleson     .          
## name2Bush         .          
## name2Butler       .          
## name2Cabell       .          
## name2Cangelosi    .          
## name2Canseco      .          
## name2Carter       .          
## name2Castillo     .          
## name2Cerone       .          
## name2Cey          .          
## name2Clark        .          
## name2Coleman      .          
## name2Coles        .          
## name2Collins      .          
## name2Concepcion   .          
## name2Cooper       .          
## name2Cruz         .          
## name2Daniels      .          
## name2Daulton      .          
## name2Davis        .          
## name2Dawson       .          
## name2DeCinces     .          
## name2Deer         .          
## name2Dempsey      .          
## name2Dernier      .          
## name2Diaz         .          
## name2Doran        .          
## name2Downing      .          
## name2Duncan       .          
## name2Dunston      .          
## name2Durham       .          
## name2Dwyer        .          
## name2Dykstra      .          
## name2Easler       .          
## name2Esasky       .          
## name2Evans        .          
## name2Fernandez    .          
## name2Fisk         .          
## name2Fitzgerald   .          
## name2Flannery     .          
## name2Fletcher     .          
## name2Foley        .          
## name2Ford         .          
## name2Foster       .          
## name2Franco       .          
## name2Gaetti       .          
## name2Gagne        .          
## name2Galarraga    .          
## name2Gantner      .          
## name2Garcia       .          
## name2Garner       .          
## name2Garvey       .          
## name2Gedman       .          
## name2Gibson       .          
## name2Gladden      .          
## name2Grich        .          
## name2Griffey      .          
## name2Griffin      .          
## name2Grubb        .          
## name2Guillen      .          
## name2Gwynn        .          
## name2Hairston     .          
## name2Hall         .          
## name2Harper       .          
## name2Harrah       .          
## name2Hassey       .          
## name2Hatcher      .          
## name2Hayes        .          
## name2Heath        .          
## name2Heep         .          
## name2Henderson    .          
## name2Hendrick     .          
## name2Hernandez    .          
## name2Herndon      .          
## name2Herr         .          
## name2Hill         .          
## name2Horner       .          
## name2Howell       .          
## name2Hrbek        .          
## name2Hubbard      .          
## name2Hulett       .          
## name2Incaviglia   .          
## name2Iorg         .          
## name2Jackson      .          
## name2Jacoby       .          
## name2Jeltz        .          
## name2Johnson      .          
## name2Jones        .          
## name2Joyner       .          
## name2Kearney      .          
## name2Kennedy      .          
## name2Kingery      .          
## name2Kingman      .          
## name2Kittle       .          
## name2Knight       .          
## name2Krenchicki   .          
## name2Kruk         .          
## name2Kutcher      .          
## name2Lacy         .          
## name2Landreaux    .          
## name2Landrum      .          
## name2Lansford     .          
## name2Laudner      .          
## name2LaValliere   .          
## name2Law          .          
## name2Leach        .          
## name2Lemon        .          
## name2Leonard      .          
## name2Lombardozzi  .          
## name2Lopes        .          
## name2Lynn         .          
## name2Madlock      .          
## name2Maldonado    .          
## name2Manning      .          
## name2Marshall     .          
## name2Martinez     .          
## name2Matthews     .          
## name2Mattingly    .          
## name2Matuszek     .          
## name2McDowell     .          
## name2McGee        .          
## name2McRae        .          
## name2McReynolds   .          
## name2Meacham      .          
## name2Melvin       .          
## name2Milner       .          
## name2Mitchell     .          
## name2Molitor      .          
## name2Moore        .          
## name2Moreland     .          
## name2Moreno       .          
## name2Morrison     .          
## name2Moseby       .          
## name2Moses        .          
## name2Motley       .          
## name2Mulliniks    .          
## name2Mumphrey     .          
## name2Murphy       .          
## name2Murray       .          
## name2Nettles      .          
## name2Newman       .          
## name2O&#39;Brien      .          
## name2O&#39;Malley     .          
## name2Oberkfell    .          
## name2Oester       .          
## name2Oglivie      .          
## name2Orsulak      .          
## name2Orta         .          
## name2Owen         .          
## name2Paciorek     .          
## name2Pagliarulo   .          
## name2Parker       .          
## name2Parrish      .          
## name2Pasqua       .          
## name2Pena         .          
## name2Pendleton    .          
## name2Perez        .          
## name2Pettis       .          
## name2Phelps       .          
## name2Phillips     .          
## name2Porter       .          
## name2Presley      .          
## name2Puckett      .          
## name2Puhl         .          
## name2Quinones     .          
## name2Quirk        .          
## name2Raines       .          
## name2Ramirez      .          
## name2Randolph     .          
## name2Ray          .          
## name2Rayford      .          
## name2Redus        .          
## name2Reed         .          
## name2Reynolds     .          
## name2Rice         .          
## name2Riles        .          
## name2Ripken       .          
## name2Rivera       .          
## name2Roberts      .          
## name2Robidoux     .          
## name2Roenicke     .          
## name2Romero       .          
## name2Rose         .          
## name2Royster      .          
## name2Russell      .          
## name2Salas        .          
## name2Salazar      .          
## name2Sample       .          
## name2Samuel       .          
## name2Sandberg     .          
## name2Santana      .          
## name2Sax          .          
## name2Schmidt      .          
## name2Schofield    .          
## name2Schroeder    .          
## name2Schu         .          
## name2Scioscia     .          
## name2Sheets       .          
## name2Shelby       .          
## name2Sheridan     .          
## name2Sierra       .          
## name2Simmons      .          
## name2Skinner      .          
## name2Slaught      .          
## name2Smalley      .          
## name2Smith        .          
## name2Snyder       .          
## name2Speier       .          
## name2Spilman      .          
## name2Stillwell    .          
## name2Stone        .          
## name2Strawberry   0.009757289
## name2Stubbs       .          
## name2Sundberg     .          
## name2Sveum        .          
## name2Tabler       .          
## name2Tartabull    .          
## name2Templeton    .          
## name2Tettleton    .          
## name2Teufel       .          
## name2Thomas       .          
## name2Thompson     .          
## name2Thon         .          
## name2Thornton     .          
## name2Tolleson     .          
## name2Traber       .          
## name2Trammell     .          
## name2Trevino      .          
## name2Upshaw       .          
## name2Uribe        .          
## name2Van Slyke    .          
## name2Virgil       .          
## name2Walker       .          
## name2Wallach      .          
## name2Walling      .          
## name2Ward         .          
## name2Webster      .          
## name2Whitaker     .          
## name2White        .          
## name2Whitt        .          
## name2Wiggins      .          
## name2Wilfong      .          
## name2Wilkerson    .          
## name2Willard      .          
## name2Williams     .          
## name2Wilson       .          
## name2Winfield     .          
## name2Winningham   .          
## name2Wynegar      .          
## name2Wynne        .          
## name2Young        .          
## name2Youngblood   .          
## name2Yount        .          
## atbat86           .          
## hits86            .          
## homer86           .          
## runs86           -0.001622108
## rbi86             .          
## walks86           .          
## years             .          
## atbat             .          
## hits              .          
## homeruns          .          
## runs              .          
## rbi               .          
## walks             .          
## div86             .          
## team86Bal        -1.644550274
## team86Bos        -1.457388067
## team86Cal        -1.605676616
## team86Chi         .          
## team86Cin         1.633018899
## team86Cle        -1.645498425
## team86Det        -1.623714191
## team86Hou         1.616899783
## team86KC         -1.587206329
## team86LA          1.563317154
## team86Mil        -1.675577963
## team86Min        -1.626963258
## team86Mon         1.519976743
## team86NY          .          
## team86Oak        -1.465833725
## team86Phi         1.588649133
## team86Pit         1.511569231
## team86SD          1.697146749
## team86Sea        -1.659991630
## team86SF          1.743552470
## team86StL         1.577541099
## team86Tex        -1.660400402
## team86Tor        -1.515114372
## sal87             .          
## prob              .          
## predicted1        .          
## logit             0.182672145</code></pre>
<pre class="r"><code>predilasfit &lt;- predict (lasso_fit, baseball_preds, tpye=&quot;response&quot;)
table(predict = as.numeric(predilasfit &gt; 0.5), truth = baseball$league86)</code></pre>
<pre><code>##        truth
## predict   0   1
##       0 139  28
##       1   0  96</code></pre>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
